# 错误和异常

## 常见的异常

- NameError：尝试访问一个未申明的变量
- ZeroDivisionError：除数为零
- SyntaxError：Python解释器语法错误
- IndexError：请求的序列超出序列范围
- KeyError：请求一个不存在的字典关键字
- IOError：输入/输出错误
- AttributeError：尝试访问未知的对象属性

## 检测处理异常

### 常用的语法

- try-except：可以跟着多个except
- try-finally：只能对应一个finally
- try-except-finally：复合形式

### try-except

```python
try:
    try_code
except Exception:
    deal_code
except (Exception1,Exception2):
    deal_code
```

### try-except-else

- 在try范围内中没有异常被检测到时，执行else中的代码

```python
try:
    try_code
except:
    dela_code
else:
    code 
```

### finally

- 无论是否有异常发生，都会执行finally中的代码

```python
try:
    try_code
except:
    dela_code
else:
    code 
finally:
    code
```

## 上下文管理

### with语句

- 条件：仅能工作于支持上下文管理协议的对象

- 包含上下文管理器的对象：

  ```markdown
  threading模块的对象：Lock，RLock，Condition，Semaphore，BoundedSemaphore
  ```

- 语法

  ```python
  with context_expr [as var]:
      with_suite
  ```

- 示例

  ```python
  with open('test.txt','r') as f:
      for eachline in f:
          print(eachline)
  ```

  
